### ISSUE TITLE
ToDo list for new version

### ISSUE THREAD

**Issue by Norbiros** [jensjeflensje/websk#52]
# This is ToDo for new release (1.3.0)!
### Important
- [x] Add way to exclude files from static web server (in config.yml)
- [x] Fix bug with variables in template tags (you cannot use variables in loops)
- [x] Add option to change static web folder (from WebSk/files to another [also in config])

### Other
- [x] Test static web server (it sometimes does not work)
- [ ] Test new template system (all features in it)

# Ideas for future releases
- [ ] Protect web server with ssl (https) (using ReverseProxy) [1.4.0]
- [ ] Add a lot of features to template system (read #41 and #45)
- [ ] Create docs (in Github Wiki)

### If you want talk with us about this, or give us ideas feel free to comment (or talk with us on our DC server)!
